### PR TITLE
Improvments

### PR DESCRIPTION
**Pull request by conradKE**

### CODE REVIEW

**Comment by StanleyMasinde** [comment]
What does this PR do?

**Review by StanleyMasinde — APPROVED** [review]
Please add a description to the PR

**Comment by conradKE** [comment]
qgydH

what PR does added illustration images

**Comment by StanleyMasinde** [comment]
Great stuff @azim254 I think it is ready to merge.
We are going to have a meeting on the org's website in the course of next week and discuss this.

**Pull request merged**
