### PR TITLE
Web-design proposal

### PR DESCRIPTION
**Pull request by miami78**
What does this PR do?
* Creates a basic web template for Opensource-254
Screenshot (417)

### CODE REVIEW

**Comment by conradKE** [comment]
hehe hi ni gani 😀😀

**Comment by billthebuilder** [comment]
> hehe hi ni gani 😀😀

I think ni template imekuwa visualized tu, I think it should be on another branch

**Comment by StanleyMasinde** [comment]
> > hehe hi ni gani grinninggrinning
> 
> I think ni template imekuwa visualized tu, I think it should be on another branch

Great Idea

**Review by Donstesh — CHANGES_REQUESTED** [review]
it looks super awesome but why dont we have some improvements like projects worked on by the teams involved in the orginisation it can be a page or just a section showing some projects worked on like the covid19 app and the covid 19 kenya pwa

**Comment by stannlee** [comment]
> it looks super awesome but why dont we have some improvements like projects worked on by the teams involved in the orginisation it can be a page or just a section showing some projects worked on like the covid19 app and the covid 19 kenya pwa

@Donstesh Please be free to create a PR 😊

**Review by StanleyMasinde — COMMENTED** [review]
Looks great. Let me see what the others think

**Comment by conradKE** [comment]
yeah its nice though it should be on another brach for comparizon or another folder

**Comment by conradKE** [comment]
this needs to be implemented
https://htmlpreview.github.io/?https://github.com/miami78/WebTemplate/blob/master/index.html

on this

https://opensource-254.github.io/WebTemplate/

**Review by StanleyMasinde — APPROVED** [review]
Looks great to me

**Comment by brianngeywo** [comment]
Screenshot from 2020-04-10 21-47-05

**Comment by conradKE** [comment]
can we move this to a diffrent brach

**Review by conradKE — CHANGES_REQUESTED** [review]
move it to a diffrent brach

**Comment by StanleyMasinde** [comment]
This PR has been merged into the miami branch

**Pull request closed without merging**
