### PR TITLE
changed margin top

### PR DESCRIPTION
**Pull request by conradKE**
what this PR does
 some changes and ui enhancement preview  [here](https://htmlpreview.github.io/?https://github.com/azim254/website-proposal/blob/master/index.html)

### CODE REVIEW

**Review by StanleyMasinde — APPROVED** [review]
Looks awesome. It is helpful if the navbar is in a fixed position which I temporarily removed.

**Comment by conradKE** [comment]
> Looks awesome. It is helpful if the navbar is in a fixed position which I temporarily removed.

if its going to have it fixed will be better but its good that way

**Comment by billthebuilder** [comment]
Halafu, @stannlee connect this with netlify inorder to view deploy previews easily

**Comment by StanleyMasinde** [comment]
> Halafu, @stannlee connect this with netlify inorder to view deploy previews easily

Good Idea

**Pull request merged**
